### ISSUE TITLE
Мобильная верстка не соответствует макету

### ISSUE THREAD

**Issue by contributeless** [Lertyj/NFT-Marketplace#20]
![image](https://github.com/Lertyj/NFT-Marketplace/assets/15820133/e0651045-49bc-4107-94b9-0db44add07a9)
![image](https://github.com/Lertyj/NFT-Marketplace/assets/15820133/ee59bfe3-c945-444b-b3a2-10675ee5679e)
![image](https://github.com/Lertyj/NFT-Marketplace/assets/15820133/6c503e24-7517-4ac9-aec1-d1e14bd2823a)
![image](https://github.com/Lertyj/NFT-Marketplace/assets/15820133/22b6eb94-46bd-4196-aa8f-9b9e059e0f08)

должно быть
![image](https://github.com/Lertyj/NFT-Marketplace/assets/15820133/07c7adb9-4f3f-42f0-8768-4c95986ad36f)

**Comment by contributeless** [comment]
в целом относится ко всем страницам

**Comment by contributeless** [comment]
и обрезается менюшка в мобильной версии
![image](https://github.com/Lertyj/NFT-Marketplace/assets/15820133/31f776d6-a377-464c-9b6c-81db992743d2)

**Comment by contributeless** [comment]
нельзя схватить мышкой горизонтальный скролл в таблице 
![image](https://github.com/Lertyj/NFT-Marketplace/assets/15820133/db4315fb-7095-4dbd-b477-f9732c7ee95b)

**Comment by Lertyj** [comment]
Теперь мобильная верстка должна соответствовать макету, а также скролл в таблице можно схватить мышкой
