### ISSUE TITLE
при навигации по подпунктам меню следует изменять роут, вместо сохранения пункта меню где-то в localstorage

### ISSUE THREAD

**Issue by contributeless** [Lertyj/NFT-Marketplace#21]
![image](https://github.com/Lertyj/NFT-Marketplace/assets/15820133/a514ad73-5384-4e48-8e40-85ea78105d2a)

**Comment by contributeless** [comment]
из-за этого есть еще и странное поведение
1) переключаешь на любой другой пункт меню
2) возвращаешься в пункт с настройками
3) ты остаешься на том табе в настройках, который был последним открыт, хотя должен открываться profile

**Comment by Lertyj** [comment]
Теперь навигация сделана через react router dom и все работает стабильно
