### ISSUE TITLE
навигация по хлебным крошкам

### ISSUE THREAD

**Issue by contributeless** [Lertyj/NFT-Marketplace#22]
![image](https://github.com/Lertyj/NFT-Marketplace/assets/15820133/f01a7063-d862-4545-84f7-200478cb9e20)
Хлебные крошки должны быть кликабельные (кроме последней части, на скрине это settings). Это дает возможность пользователю вернуться на уровень или несколько уровней выше от того места, где он находится. При нажатии на home надо переходить на home)

**Comment by Lertyj** [comment]
Теперь присутствует навигация по хлебным крошкам, так же при наведении на Home сделана анимация.
