### ISSUE TITLE
позиция навбара

### ISSUE THREAD

**Issue by contributeless** [Lertyj/NFT-Marketplace#25]
весь навбар должен быть прибит к левой стороне экрана
![image](https://github.com/Lertyj/NFT-Marketplace/assets/15820133/9b220d07-530e-40f8-97a3-82685f5b99bf)

**Comment by contributeless** [comment]
воспроизводится на широком экране)

**Comment by Lertyj** [comment]
Теперь SideBar прижат все время к левой стороне экрана
