### ISSUE TITLE
неверный подход к обработке пунктов меню

### ISSUE THREAD

**Issue by contributeless** [Lertyj/NFT-Marketplace#26]
![image](https://github.com/Lertyj/NFT-Marketplace/assets/15820133/2fe1fbfc-a403-425f-bd1f-d8ecb1afcfe5)

нет необходимости сохранять текущий пункт меню в localstorage - эта информация уже хранится в текущем урле

я локально удалил это всё, и оно уже работает) разберись, пожалуйста, как работает react-router

**Comment by Lertyj** [comment]
Теперь выбранный пункт меню не сохраняется в local storage
