### ISSUE TITLE
выбор темы должен быть дропдауном

### ISSUE THREAD

**Issue by contributeless** [Lertyj/NFT-Marketplace#27]
![image](https://github.com/Lertyj/NFT-Marketplace/assets/15820133/186514cb-e6b7-4145-aa8f-efa9a110ecc7)

концептуально - это выпадающий список с одним вариантом выбора

надо использовать тег select) со стилизацией будет больно, но это возможно

**Comment by Lertyj** [comment]
Теперь выбор темы реализован при помощи react-select
