### ISSUE TITLE
работа с темами

### ISSUE THREAD

**Issue by contributeless** [Lertyj/NFT-Marketplace#28]
![image](https://github.com/Lertyj/NFT-Marketplace/assets/15820133/9993ed2e-b576-4d2d-9635-f00c7b5ef4b7)
При разработке react-приложений рекомендуется не обращаться к dom-дереву напрямую

это оправдано только в одном случае) когда рендеришь всю свою апку в какой-то элемент

в остальном всё должно происходить силами реакта

также не круто, что какой-то компонент изменяет состояние рутового элемента.

немного я другое имел в виду, когда говорил про ThemeManager

Предполагалось, что есть класс ThemeManager, который знает текущую тему, например dark, знает список всех тем, например dark, light, darkLight, а также умеет сохранять текущую тему и доставать из localstorage. Еще он может по названию темы возвращать иконку к ней, например. При этом этот класс не является реакт-компонентом, он сам нигде не рендерится

И есть компонент, который занимается рендерингом, например, называется ThemeSelector. В нём уже ты рисуешь свой дропдаун с темами, подсвечиваешь текущую на основе того, что возвращает ему ThemeManager.

Плюс в рутовой компоненте тоже дергаешь themeManager, получаешь текущую тему и проставляешь свой data-theme атрибут, причем не через appElement.setAttribute, а средствами реакта <MyCoolComponent dataTheme={currentTheme}>

**Comment by Lertyj** [comment]
Сделано
