### ISSUE TITLE
Название файлов должно соответствовать тому, что внутри

### ISSUE THREAD

**Issue by contributeless** [Lertyj/NFT-Marketplace#29]
![image](https://github.com/Lertyj/NFT-Marketplace/assets/15820133/1d680b9c-eb9a-410d-bb97-e00c53e351ad)
![image](https://github.com/Lertyj/NFT-Marketplace/assets/15820133/819293ab-a58a-43c5-b24e-e1d7598b0a69)

Названия должны быть один в один, плюс не клади несколько компонентов в один файл. один компонент/один класс - один файл

**Comment by Lertyj** [comment]
На данный момент эта issue исправлена
